/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.robotcup.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 05-10-2014
 * 
 * XDoclet definition:
 * @struts.form name="adminInfoForm"
 */
public class AdminInfoForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** adminemail property */
	private String adminemail;

	/** adminname property */
	private String adminname;
	
	private int adminid;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the adminemail.
	 * @return String
	 */
	public String getAdminemail() {
		return adminemail;
	}

	/** 
	 * Set the adminemail.
	 * @param adminemail The adminemail to set
	 */
	public void setAdminemail(String adminemail) {
		this.adminemail = adminemail;
	}

	/** 
	 * Returns the adminname.
	 * @return String
	 */
	public String getAdminname() {
		return adminname;
	}

	/** 
	 * Set the adminname.
	 * @param adminname The adminname to set
	 */
	public void setAdminname(String adminname) {
		this.adminname = adminname;
	}

	public int getAdminid() {
		return adminid;
	}

	public void setAdminid(int adminid) {
		this.adminid = adminid;
	}
}