/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.robotcup.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

/** 
 * MyEclipse Struts
 * Creation date: 04-18-2014
 * 
 * XDoclet definition:
 * @struts.form name="articleForm"
 */
public class ArticleForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** mname property */
	private String mtitle;

	/** mcontent property */
	private String mcontent;

	/** attid property */
	private Integer atid;

	/** mtop property */
	private Integer mtop;

	/** mattachment property */
	private FormFile mattachment;
	
	private Integer adid;
	
	//更新要用到的属性
	private String md5name;
	
	private String relname;
	
	
	private Integer nid;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the mtitle.
	 * @return String
	 */
	public String getMtitle() {
		return mtitle;
	}

	/** 
	 * Set the mtitle.
	 * @param mtitle The mtitle to set
	 */
	public void setMtitle(String mtitle) {
		this.mtitle = mtitle;
	}

	/** 
	 * Returns the mcontent.
	 * @return String
	 */
	public String getMcontent() {
		return mcontent;
	}

	/** 
	 * Set the mcontent.
	 * @param mcontent The mcontent to set
	 */
	public void setMcontent(String mcontent) {
		this.mcontent = mcontent;
	}

	/** 
	 * Returns the attid.
	 * @return Integer
	 */
	public Integer getAtid() {
		return atid;
	}

	/** 
	 * Set the attid.
	 * @param attid The attid to set
	 */
	public void setAtid(Integer atid) {
		this.atid = atid;
	}

	/** 
	 * Returns the mtop.
	 * @return Integer
	 */
	public Integer getMtop() {
		return mtop;
	}

	/** 
	 * Set the mtop.
	 * @param mtop The mtop to set
	 */
	public void setMtop(Integer mtop) {
		this.mtop = mtop;
	}

	/** 
	 * Returns the mattachment.
	 * @return File
	 */
	public FormFile getMattachment() {
		return mattachment;
	}

	/** 
	 * Set the mattachment.
	 * @param mattachment The mattachment to set
	 */
	public void setMattachment(FormFile mattachment) {
		this.mattachment = mattachment;
	}

	public Integer getAdid() {
		return adid;
	}

	public void setAdid(Integer adid) {
		this.adid = adid;
	}

	public Integer getNid() {
		return nid;
	}

	public void setNid(Integer nid) {
		this.nid = nid;
	}

	public String getMd5name() {
		return md5name;
	}

	public void setMd5name(String md5name) {
		this.md5name = md5name;
	}

	public String getRelname() {
		return relname;
	}

	public void setRelname(String relname) {
		this.relname = relname;
	}
}