/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.robotcup.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 05-01-2014
 * 
 * XDoclet definition:
 * @struts.form name="itemsTypeForm"
 */
public class ItemsTypeForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** tyname property */
	private String tyname;

	/** tyid property */
	private Integer tyid;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the tyname.
	 * @return String
	 */
	public String getTyname() {
		return tyname;
	}

	/** 
	 * Set the tyname.
	 * @param tyname The tyname to set
	 */
	public void setTyname(String tyname) {
		this.tyname = tyname;
	}

	/** 
	 * Returns the tyid.
	 * @return Integer
	 */
	public Integer getTyid() {
		return tyid;
	}

	/** 
	 * Set the tyid.
	 * @param tyid The tyid to set
	 */
	public void setTyid(Integer tyid) {
		this.tyid = tyid;
	}
}