/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.robotcup.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-17-2014
 * 
 * XDoclet definition:
 * @struts.form name="teamMemberForm"
 */
public class TeamMemberForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** mname property */
	private String mname;

	/** memail property */
	private String memail;

	/** mleader property */
	private Integer mleader;

	/** mgender property */
	private String mgender;

	/** mtype property */
	private String mtype;

	/** mphone property */
	private String mphone;

	private int tid;
	
	private int mid;
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the mname.
	 * @return String
	 */
	public String getMname() {
		return mname;
	}

	/** 
	 * Set the mname.
	 * @param mname The mname to set
	 */
	public void setMname(String mname) {
		this.mname = mname;
	}

	/** 
	 * Returns the memail.
	 * @return String
	 */
	public String getMemail() {
		return memail;
	}

	/** 
	 * Set the memail.
	 * @param memail The memail to set
	 */
	public void setMemail(String memail) {
		this.memail = memail;
	}

	/** 
	 * Returns the mleader.
	 * @return Integer
	 */
	public Integer getMleader() {
		return mleader;
	}

	/** 
	 * Set the mleader.
	 * @param mleader The mleader to set
	 */
	public void setMleader(Integer mleader) {
		this.mleader = mleader;
	}

	/** 
	 * Returns the mgender.
	 * @return String
	 */
	public String getMgender() {
		return mgender;
	}

	/** 
	 * Set the mgender.
	 * @param mgender The mgender to set
	 */
	public void setMgender(String mgender) {
		this.mgender = mgender;
	}

	/** 
	 * Returns the mtype.
	 * @return String
	 */
	public String getMtype() {
		return mtype;
	}

	/** 
	 * Set the mtype.
	 * @param mtype The mtype to set
	 */
	public void setMtype(String mtype) {
		this.mtype = mtype;
	}

	/** 
	 * Returns the mphone.
	 * @return String
	 */
	public String getMphone() {
		return mphone;
	}

	/** 
	 * Set the mphone.
	 * @param mphone The mphone to set
	 */
	public void setMphone(String mphone) {
		this.mphone = mphone;
	}

	public int getTid() {
		return tid;
	}

	public void setTid(int tid) {
		this.tid = tid;
	}

	public int getMid() {
		return mid;
	}

	public void setMid(int mid) {
		this.mid = mid;
	}
}