/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.robotcup.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 05-01-2014
 * 
 * XDoclet definition:
 * @struts.form name="teamItemsForm"
 */
public class TeamItemsForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** tyid property */
	private Integer tyid;

	/** itname property */
	private String itname;

	/** itid property */
	private Integer itid;
	
	private Integer itlimit;
	
	private String itremark;
	
	private Integer ittealim;
	
	private Integer itteacap;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the tyid.
	 * @return Integer
	 */
	public Integer getTyid() {
		return tyid;
	}

	/** 
	 * Set the tyid.
	 * @param tyid The tyid to set
	 */
	public void setTyid(Integer tyid) {
		this.tyid = tyid;
	}

	/** 
	 * Returns the itname.
	 * @return String
	 */
	public String getItname() {
		return itname;
	}

	/** 
	 * Set the itname.
	 * @param itname The itname to set
	 */
	public void setItname(String itname) {
		this.itname = itname;
	}

	/** 
	 * Returns the itid.
	 * @return Integer
	 */
	public Integer getItid() {
		return itid;
	}

	/** 
	 * Set the itid.
	 * @param itid The itid to set
	 */
	public void setItid(Integer itid) {
		this.itid = itid;
	}

	public Integer getItlimit() {
		return itlimit;
	}

	public void setItlimit(Integer itlimit) {
		this.itlimit = itlimit;
	}

	public String getItremark() {
		return itremark;
	}

	public void setItremark(String itremark) {
		this.itremark = itremark;
	}

	public Integer getIttealim() {
		return ittealim;
	}

	public void setIttealim(Integer ittealim) {
		this.ittealim = ittealim;
	}

	public Integer getItteacap() {
		return itteacap;
	}

	public void setItteacap(Integer itteacap) {
		this.itteacap = itteacap;
	}
}