/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.robotcup.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 05-01-2014
 * 
 * XDoclet definition:
 * @struts.form name="teamAdminForm"
 */
public class TeamAdminForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** adid property */
	private Integer adid;

	/** adpwd property */
	private String adpwd;

	/** aid property */
	private Integer aid;

	/** adname property */
	private String adname;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the adid.
	 * @return Integer
	 */
	public Integer getAdid() {
		return adid;
	}

	/** 
	 * Set the adid.
	 * @param adid The adid to set
	 */
	public void setAdid(Integer adid) {
		this.adid = adid;
	}

	/** 
	 * Returns the adpwd.
	 * @return String
	 */
	public String getAdpwd() {
		return adpwd;
	}

	/** 
	 * Set the adpwd.
	 * @param adpwd The adpwd to set
	 */
	public void setAdpwd(String adpwd) {
		this.adpwd = adpwd;
	}

	/** 
	 * Returns the aid.
	 * @return Integer
	 */
	public Integer getAid() {
		return aid;
	}

	/** 
	 * Set the aid.
	 * @param aid The aid to set
	 */
	public void setAid(Integer aid) {
		this.aid = aid;
	}

	/** 
	 * Returns the adname.
	 * @return String
	 */
	public String getAdname() {
		return adname;
	}

	/** 
	 * Set the adname.
	 * @param adname The adname to set
	 */
	public void setAdname(String adname) {
		this.adname = adname;
	}
}