/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.robotcup.struts.action;

import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.springframework.stereotype.Controller;

import com.robotcup.domain.TeamAdmin;
import com.robotcup.service.imp.TeamAdminServiceImp;
import com.robotcup.struts.form.TeamAdminForm;
import com.robotcup.util.MyTools;

/** 
 * MyEclipse Struts
 * Creation date: 05-01-2014
 * 
 * XDoclet definition:
 * @struts.action path="/addAdmin" name="teamAdminForm" scope="request" validate="true"
 */
@Controller
public class AddAdminAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */

	@Resource
	private TeamAdminServiceImp teamAdminServiceImp;
	public TeamAdminServiceImp getTeamAdminServiceImp() {
		return teamAdminServiceImp;
	}
	public void setTeamAdminServiceImp(TeamAdminServiceImp teamAdminServiceImp) {
		this.teamAdminServiceImp = teamAdminServiceImp;
	}
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		TeamAdminForm teamAdminForm = (TeamAdminForm) form;// TODO Auto-generated method stub
		if(!teamAdminServiceImp.isAdminRepeat(teamAdminForm.getAdname()))
		{
			TeamAdmin teamAdmin=new TeamAdmin();
			teamAdmin.setAdname(teamAdminForm.getAdname());
			teamAdmin.setAdpwd(MyTools.MD5(teamAdminForm.getAdpwd()));
			teamAdmin.setTeamArea(teamAdminServiceImp.getTeamAreaByAid(teamAdminForm.getAid()));
			teamAdminServiceImp.addAdmin(teamAdmin);
			request.setAttribute("addres", 1);
		}
		else
			request.setAttribute("addres", 0);
		List<TeamAdmin> adlist=teamAdminServiceImp.getTeamAdmin();
		request.getSession().setAttribute("adlist", adlist);
		request.getSession().setAttribute("adform", teamAdminForm);
		return mapping.findForward("ok");
	}
}