/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.robotcup.struts.action;

import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.springframework.stereotype.Controller;

import com.robotcup.domain.TeamArea;
import com.robotcup.service.imp.ExecuteQueryImp;
import com.robotcup.service.imp.TeamAdminServiceImp;
import com.robotcup.struts.form.TeamAreaForm;

/** 
 * MyEclipse Struts
 * Creation date: 05-01-2014
 * 
 * XDoclet definition:
 * @struts.action path="/addArea" name="teamAreaForm" scope="request" validate="true"
 */
@Controller
public class AddAreaAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	@Resource
	private TeamAdminServiceImp teamAdminServiceImp;
	public TeamAdminServiceImp getTeamAdminServiceImp() {
		return teamAdminServiceImp;
	}
	public void setTeamAdminServiceImp(TeamAdminServiceImp teamAdminServiceImp) {
		this.teamAdminServiceImp = teamAdminServiceImp;
	}
	@Resource
	private ExecuteQueryImp executeQueryImp;
	public ExecuteQueryImp getExecuteQueryImp() {
		return executeQueryImp;
	}
	public void setExecuteQueryImp(ExecuteQueryImp executeQueryImp) {
		this.executeQueryImp = executeQueryImp;
	}
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		TeamAreaForm teamAreaForm = (TeamAreaForm) form;// TODO Auto-generated method stub
		//没有重名的才能添加
		if(!teamAdminServiceImp.isAreaRepeat(teamAreaForm.getAname()))
		{
			TeamArea teamArea=new TeamArea();
			teamArea.setAname(teamAreaForm.getAname());
			teamAdminServiceImp.addArea(teamArea);
			request.setAttribute("addres", 1);//1表示添加成功
		}
		else
			request.setAttribute("addres", 0);//表示有重名	
		List<TeamArea> alist=executeQueryImp.getArea();
		request.getSession().setAttribute("alist", alist);
		return mapping.findForward("ok");
	}
}