/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.robotcup.struts.action;

import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.springframework.stereotype.Controller;

import com.robotcup.domain.TeamUnversity;
import com.robotcup.service.imp.ExecuteQueryImp;
import com.robotcup.service.imp.TeamAdminServiceImp;
import com.robotcup.struts.form.TeamUnversityForm;

/** 
 * MyEclipse Struts
 * Creation date: 05-01-2014
 * 
 * XDoclet definition:
 * @struts.action path="/addUnversity" name="teamUnversityForm" scope="request" validate="true"
 */
@Controller
public class AddUnversityAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	@Resource
	private TeamAdminServiceImp teamAdminServiceImp;
	public TeamAdminServiceImp getTeamAdminServiceImp() {
		return teamAdminServiceImp;
	}
	public void setTeamAdminServiceImp(TeamAdminServiceImp teamAdminServiceImp) {
		this.teamAdminServiceImp = teamAdminServiceImp;
	}
	@Resource
	private ExecuteQueryImp executeQueryImp;
	public ExecuteQueryImp getExecuteQueryImp() {
		return executeQueryImp;
	}
	public void setExecuteQueryImp(ExecuteQueryImp executeQueryImp) {
		this.executeQueryImp = executeQueryImp;
	}
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		TeamUnversityForm teamUnversityForm = (TeamUnversityForm) form;// TODO Auto-generated method stub
		if(!teamAdminServiceImp.isUnversityRepeat(teamUnversityForm.getSname()))
		{
			TeamUnversity teamUnversity=new TeamUnversity();
			teamUnversity.setSname(teamUnversityForm.getSname());
			teamUnversity.setTeamArea(teamAdminServiceImp.getTeamAreaByAid(teamUnversityForm.getAid()));
			teamAdminServiceImp.addUnversity(teamUnversity);
			request.setAttribute("addres", 1);//添加成功
		}
		else
			request.setAttribute("addres", 0);//有重名
		List<TeamUnversity> slist=executeQueryImp.getUniversity();
		request.getSession().setAttribute("slist", slist);
		request.getSession().setAttribute("sform", teamUnversityForm);//保留页面上已经输入的内容
		return mapping.findForward("ok");
	}
}