/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.robotcup.struts.action;

import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import org.springframework.stereotype.Controller;

import com.robotcup.domain.RobotAttachment;
import com.robotcup.domain.RobotNews;
import com.robotcup.parameter.Parameters;
import com.robotcup.pojo.NewsImp;
import com.robotcup.service.imp.ExecuteQueryImp;
import com.robotcup.service.imp.PublishServiceImp;

/** 
 * MyEclipse Struts
 * Creation date: 04-28-2014
 * 
 * XDoclet definition:
 * @struts.action
 */
@Controller
public class ArticleManageAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	@Resource
	private PublishServiceImp publishServiceImp;
	public PublishServiceImp getPublishServiceImp() {
		return publishServiceImp;
	}
	public void setPublishServiceImp(PublishServiceImp publishServiceImp) {
		this.publishServiceImp = publishServiceImp;
	}
	@Resource
	private ExecuteQueryImp executeQueryImp;
	public ExecuteQueryImp getExecuteQueryImp() {
		return executeQueryImp;
	}
	public void setExecuteQueryImp(ExecuteQueryImp executeQueryImp) {
		this.executeQueryImp = executeQueryImp;
	}
	public ActionForward del(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		int nid=Integer.parseInt(request.getParameter("nid"));
		publishServiceImp.delRobotNewsByNid(nid);

		int pageNum=1;
		String pageNum_=request.getParameter("pageNum");
		if(pageNum_!=null)
			pageNum=Integer.parseInt(pageNum_);
		//删除消息后再跳回管理界面
		List<NewsImp> allnewslist=publishServiceImp.getAllRobotNews(pageNum,Parameters.NEWSPAGESIZE);
		request.getSession().setAttribute("allnews", allnewslist);

		int pageSum=publishServiceImp.getPageSumByAtid(0, Parameters.NEWSPAGESIZE);
		request.getSession().setAttribute("pageSum", pageSum==0?1:pageSum);
		request.getSession().setAttribute("pageNum", pageNum);
		return mapping.findForward("show");
	}
	public ActionForward page(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response){

		int pageNum=1;
		String pageNum_=request.getParameter("pageNum");
		if(pageNum_!=null)
			pageNum=Integer.parseInt(pageNum_);
		
		List<NewsImp> allnewslist=publishServiceImp.getAllRobotNews(pageNum,Parameters.NEWSPAGESIZE);
		request.getSession().setAttribute("allnews", allnewslist);

		int pageSum=publishServiceImp.getPageSumByAtid(0, Parameters.NEWSPAGESIZE);//0表示获取全部模块的新闻总数
		request.getSession().setAttribute("pageSum", pageSum==0?1:pageSum);
		request.getSession().setAttribute("pageNum", pageNum);
		return mapping.findForward("show");
	}
	public ActionForward update(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response){

		int nid=Integer.parseInt(request.getParameter("nid"));
		RobotNews rn=publishServiceImp.getNewsByNid(nid);
		request.getSession().setAttribute("upart", rn);
		
		List<RobotAttachment> attachment=executeQueryImp.getAllAttachment();
		attachment.remove(attachment.size()-1);//去掉附件下载
		attachment.remove(attachment.size()-1);//去掉首页展示
		request.getSession().setAttribute("attlist", attachment);
		return mapping.findForward("update");
	}
}