/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.robotcup.struts.action;

import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import org.springframework.stereotype.Controller;

import com.robotcup.domain.RobotNews;
import com.robotcup.pojo.NewsImp;
import com.robotcup.service.imp.PublishServiceImp;

/** 
 * MyEclipse Struts
 * Creation date: 04-21-2014
 * 
 * XDoclet definition:
 * @struts.action parameter="method"
 */
@Controller
public class ArticleShowAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	@Resource
	private PublishServiceImp publishServiceImp;
	public PublishServiceImp getPublishServiceImp() {
		return publishServiceImp;
	}
	public void setPublishServiceImp(PublishServiceImp publishServiceImp) {
		this.publishServiceImp = publishServiceImp;
	}
	public ActionForward intro(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		//获取用户指定的文章
		int nid=Integer.parseInt(request.getParameter("nid"));
		RobotNews rn=publishServiceImp.getNewsByNid(nid);
		request.getSession().setAttribute("rn", rn);
		
		//获取10条相关文章列表
		List<NewsImp> relist=publishServiceImp.getNewsByAtid(rn.getRobotAttachment().getAtid(), 1, 10);
		request.getSession().setAttribute("relation", relist);
		
		return mapping.findForward("show");
	}
}