/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.robotcup.struts.action;

import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;


/** 
 * MyEclipse Struts
 * Creation date: 04-22-2014
 * 
 * XDoclet definition:
 * @struts.action
 */
public class DownloadAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		String name = request.getParameter("name");
		String relname_ = request.getParameter("relname");
		String relname="";
		try {
			//虽然有过滤器，但是IE8上依然有乱码，需要转码
			relname = new String(relname_.getBytes("iso-8859-1"),"utf-8");
		} catch (UnsupportedEncodingException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		
        BufferedInputStream bis = null;
        BufferedOutputStream bos = null;
        OutputStream fos = null;
        InputStream fis = null;
        
        String filepath= this.getServlet().getServletContext().getRealPath("/file/"+name);
        File uploadFile = new File(filepath);
        try {
        	 fis = new FileInputStream(uploadFile);
 	        bis = new BufferedInputStream(fis);
 	        fos = response.getOutputStream();
 	        bos = new BufferedOutputStream(fos);
 	        //这个就就是弹出下载对话框的关键代码
 	        response.setHeader("Content-disposition","attachment;filename=" +URLEncoder.encode(relname, "utf-8"));
 	        int bytesRead = 0;
 	        //用输入流进行先读，然后用输出流去写
 	        byte[] buffer = new byte[1024];
 	        while ((bytesRead = bis.read(buffer, 0, 1024)) != -1) {
 	            bos.write(buffer, 0, bytesRead);
 	        }
 	        bos.flush();
	        fis.close();
	        bis.close();
	        fos.close();
	        bos.close();
			
		} catch (Exception e) {
			e.printStackTrace();	       
			try {
				if(fis!=null)fis.close();
				if(bis!=null)bis.close();
				if(fos!=null)fos.close();
				if(bos!=null)bos.close();
			} catch (IOException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
		}       
        return null;
	}
}