/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.robotcup.struts.action;

import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import org.springframework.stereotype.Controller;

import com.robotcup.domain.RobotNews;
import com.robotcup.service.imp.PublishServiceImp;

/** 
 * MyEclipse Struts
 * Creation date: 05-04-2014
 * 
 * XDoclet definition:
 * @struts.action parameter="method"
 */
@Controller
public class ManageImageAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	@Resource
	private PublishServiceImp publishServiceImp;
	public PublishServiceImp getPublishServiceImp() {
		return publishServiceImp;
	}
	public void setPublishServiceImp(PublishServiceImp publishServiceImp) {
		this.publishServiceImp = publishServiceImp;
	}
	public ActionForward del(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		int nid=Integer.parseInt(request.getParameter("nid"));
		publishServiceImp.delRobotNewsByNid(nid);
		
		List<RobotNews> imglist=publishServiceImp.getTenNewsByAtid(10);//获取首页展示的图片
		request.getSession().setAttribute("imglist", imglist);
		return mapping.findForward("show");
	}
	public ActionForward redi(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		
		List<RobotNews> imglist=publishServiceImp.getTenNewsByAtid(10);//获取首页展示的图片
		request.getSession().setAttribute("imglist", imglist);
		return mapping.findForward("show");
	}
}