/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.robotcup.struts.action;

import java.util.Date;
import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import org.springframework.stereotype.Controller;

import com.robotcup.domain.TeamAdmin;
import com.robotcup.parameter.Parameters;
import com.robotcup.pojo.TeamInfo;
import com.robotcup.service.imp.ExecuteQueryImp;

/**
 * MyEclipse Struts Creation date: 04-14-2014
 * 
 * XDoclet definition:
 * 
 * @struts.action parameter="method"
 */
@Controller
public class ManageTeamsAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	@Resource
	private ExecuteQueryImp executeQueryImp;

	public ExecuteQueryImp getExecuteQueryImp() {
		return executeQueryImp;
	}

	public void setExecuteQueryImp(ExecuteQueryImp executeQueryImp) {
		this.executeQueryImp = executeQueryImp;
	}

	public ActionForward showteams(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		// 获取当前页面
		int pageNum = 1;
		String pageNum_ = request.getParameter("pageNum");
		String year = request.getParameter("year");
		if (year == null) {
			Object oyear = request.getSession().getAttribute("curYear");
			if (oyear == null)
				year = (new Date().getYear() + 1900) + "";
			else
				year = Integer.parseInt(oyear.toString()) + "";
		}
		if (pageNum_ != null)
			pageNum = Integer.parseInt(pageNum_);
		TeamAdmin ta = (TeamAdmin) request.getSession().getAttribute(
				"teamadmin");
		int aid = 0;
		if (ta != null)
			aid = ta.getTeamArea().getAid();
		List<TeamInfo> list = executeQueryImp.getTeamInfoByAid(aid, 1,
				Parameters.APPPAGESIZE, year);
		request.getSession().setAttribute("teamInfo", list);

		int pageSum = executeQueryImp.getTeamPageSum(aid,
				Parameters.APPPAGESIZE, year);

		request.getSession().setAttribute("pageNum", pageNum);
		request.getSession().setAttribute("pageSum", pageSum);
		request.getSession().setAttribute("curYear", year);
		request.getSession().setAttribute("schoolcount",
				executeQueryImp.getSchoolCount(aid, year));
		return mapping.findForward("showteams");
	}

	public ActionForward page(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		// 获取当前页面
		int pageNum = 1;
		String pageNum_ = request.getParameter("pageNum");
		String year = request.getParameter("year");
		if (year == null) {
			Object oyear = request.getSession().getAttribute("curYear");
			if (oyear == null)
				year = (new Date().getYear() + 1900) + "";
			else
				year = Integer.parseInt(oyear.toString()) + "";
		}
		if (pageNum_ != null)
			pageNum = Integer.parseInt(pageNum_);
		TeamAdmin ta = (TeamAdmin) request.getSession().getAttribute(
				"teamadmin");
		int aid = 0;
		if (ta != null)
			aid = ta.getTeamArea().getAid();
		List<TeamInfo> list = executeQueryImp.getTeamInfoByAid(aid, pageNum,
				Parameters.APPPAGESIZE, year);
		request.getSession().setAttribute("teamInfo", list);
		request.getSession().setAttribute("pageNum", pageNum);
		request.getSession().setAttribute("curYear", year);

		int pageSum = executeQueryImp.getTeamPageSum(aid,
				Parameters.APPPAGESIZE, year);

		request.getSession().setAttribute("schoolcount",
				executeQueryImp.getSchoolCount(aid, year));
		request.getSession().setAttribute("pageSum", pageSum);
		return mapping.findForward("showteams");
	}
}