/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.robotcup.struts.action;

import java.util.Date;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import org.springframework.stereotype.Controller;

import com.robotcup.domain.RobotLetter;
import com.robotcup.service.imp.ExecuteQueryImp;
import com.robotcup.service.imp.PublishServiceImp;
import com.robotcup.service.imp.TeamAdminServiceImp;
import com.robotcup.service.imp.TeamManageServiceImp;
import com.robotcup.struts.form.LetterForm;

/** 
 * MyEclipse Struts
 * Creation date: 05-04-2014
 * 
 * XDoclet definition:
 * @struts.action path="/publishLetter" name="letterForm" scope="request" validate="true"
 */
@Controller
public class PublishLetterAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	@Resource
	private ExecuteQueryImp executeQueryImp;
	public ExecuteQueryImp getExecuteQueryImp() {
		return executeQueryImp;
	}
	public void setExecuteQueryImp(ExecuteQueryImp executeQueryImp) {
		this.executeQueryImp = executeQueryImp;
	}
	@Resource
	private PublishServiceImp publishServiceImp;
	public PublishServiceImp getPublishServiceImp() {
		return publishServiceImp;
	}
	public void setPublishServiceImp(PublishServiceImp publishServiceImp) {
		this.publishServiceImp = publishServiceImp;
	}
	@Resource
	private TeamManageServiceImp teamManageServiceImp;
	public TeamManageServiceImp getTeamManageServiceImp() {
		return teamManageServiceImp;
	}
	public void setTeamManageServiceImp(TeamManageServiceImp teamManageServiceImp) {
		this.teamManageServiceImp = teamManageServiceImp;
	}
	public ActionForward pub(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		LetterForm letterForm = (LetterForm) form;// TODO Auto-generated method stub
		RobotLetter nrl=new RobotLetter();
		nrl.setLtitle(letterForm.getLtitle());
		nrl.setLcontent(letterForm.getLcontent());
		nrl.setLdate(new Date());
		nrl.setTeamAdmin(teamManageServiceImp.getTeamAdminByAdid(letterForm.getAdid()));
		
		publishServiceImp.addLetter(nrl);		
		
		RobotLetter rl=executeQueryImp.getRobotLetter();
		request.getSession().setAttribute("let", rl);
		return mapping.findForward("show");
	}

	public ActionForward show(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		RobotLetter rl=executeQueryImp.getRobotLetter();
		request.getSession().setAttribute("let", rl);
		return mapping.findForward("show");
	}
	public ActionForward redi(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		return mapping.findForward("publish");
	}
}