/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.robotcup.struts.action;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import org.springframework.stereotype.Controller;

import com.robotcup.domain.TeamArea;
import com.robotcup.domain.TeamUnversity;
import com.robotcup.service.imp.ExecuteQueryImp;
import com.robotcup.service.imp.TeamAdminServiceImp;

/**
 * MyEclipse Struts Creation date: 05-01-2014
 * 
 * XDoclet definition:
 * 
 * @struts.action parameter="method"
 */
@Controller
public class RedirectAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	@Resource
	private ExecuteQueryImp executeQueryImp;
	@Resource
	private TeamAdminServiceImp teamAdminServiceImp;

	public TeamAdminServiceImp getTeamAdminServiceImp() {
		return teamAdminServiceImp;
	}

	public void setTeamAdminServiceImp(TeamAdminServiceImp teamAdminServiceImp) {
		this.teamAdminServiceImp = teamAdminServiceImp;
	}

	public ExecuteQueryImp getExecuteQueryImp() {
		return executeQueryImp;
	}

	public void setExecuteQueryImp(ExecuteQueryImp executeQueryImp) {
		this.executeQueryImp = executeQueryImp;
	}

	public ActionForward login(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		request.getSession().setAttribute("isCheckCode", 0);// 表示当前登录不需要验证码
		return mapping.findForward("login");
	}

	public ActionForward register(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		boolean ent = teamAdminServiceImp.getEntrance();
		if (!ent) {
			response.setContentType("text/html;charset=utf-8");
			PrintWriter out;
			try {
				out = response.getWriter();
				out.println("<script language='javascript' type='text/javascript'>");
				out.println("alert('报名入口已经关闭，无法报名!');window.location.href='"
						+ request.getContextPath() + "/index.do'");
				out.println("</script>");
				out.flush();
				out.close();
				return null;
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		List<TeamArea> areaList = executeQueryImp.getArea();
		List<TeamUnversity> universtiyList = executeQueryImp
				.getUniversityByAid(1);// 默认显示北京赛区
		request.getSession().setAttribute("areaList", areaList);
		request.getSession().setAttribute("universityList", universtiyList);
		return mapping.findForward("reg");
	}
}