/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.robotcup.struts.action;

import java.io.PrintWriter;
import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import org.springframework.stereotype.Controller;

import com.robotcup.domain.TeamArea;
import com.robotcup.domain.TeamUnversity;
import com.robotcup.domain.TeamUser;
import com.robotcup.service.imp.ExecuteQueryImp;
import com.robotcup.service.imp.TeamManageServiceImp;
import com.robotcup.struts.form.TeamUserForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-30-2014
 * 
 * XDoclet definition:
 * @struts.action parameter="method" validate="true"
 */
@Controller
public class UpdateTeamInfoAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	@Resource
	private ExecuteQueryImp executeQueryImp;
	public ExecuteQueryImp getExecuteQueryImp() {
		return executeQueryImp;
	}
	public void setExecuteQueryImp(ExecuteQueryImp executeQueryImp) {
		this.executeQueryImp = executeQueryImp;
	}
	@Resource
	private TeamManageServiceImp teamManageServiceImp;
	public TeamManageServiceImp getTeamManageServiceImp() {
		return teamManageServiceImp;
	}
	public void setTeamManageServiceImp(TeamManageServiceImp teamManageServiceImp) {
		this.teamManageServiceImp = teamManageServiceImp;
	}
	public ActionForward team_baseinfo(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("showbaseinfo");
	}
	public ActionForward team_baseinfo_update(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		List<TeamArea> areaList=executeQueryImp.getArea();
		List<TeamUnversity> universtiyList=executeQueryImp.getUniversityByAid(1);//默认显示北京赛区
		request.getSession().setAttribute("areaList", areaList);
		request.getSession().setAttribute("universityList", universtiyList);
		return mapping.findForward("updatebaseinfo");
	}
	public ActionForward change(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		TeamUserForm tuf=(TeamUserForm) form;
		int tid=Integer.parseInt(request.getParameter("tid"));
		if(!teamManageServiceImp.isRepeat(tuf.getTname(),tid))
		{
			teamManageServiceImp.changeTeamInfo(tid, tuf);
			TeamUser teamuser=teamManageServiceImp.getTeamUserByTid(tid);
			request.getSession().setAttribute("teamuser", teamuser);
			return mapping.findForward("showbaseinfo");
		}
		else
		{
			try{
				response.setContentType("text/html;charset=utf-8");  
				PrintWriter out = response.getWriter();
				out.println("<script language='javascript' type='text/javascript'>");  
				out.println("alert('队名已经存在，请重新填写!');window.location.href='" + request.getContextPath() + "/updateTeamInfo.do?method=team_baseinfo_update'");  
				out.println("</script>");
				out.close();
			}
			catch(Exception e){			
			}
			return null;
		}
	}
}