/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.robotcup.struts.action;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.springframework.stereotype.Controller;

import com.robotcup.domain.TeamAdmin;
import com.robotcup.service.imp.TeamAdminServiceImp;
import com.robotcup.struts.form.AdminInfoForm;

/** 
 * MyEclipse Struts
 * Creation date: 05-10-2014
 * 
 * XDoclet definition:
 * @struts.action path="/updateAdminInfo" name="adminInfoForm" scope="request" validate="true"
 */
@Controller
public class UpdateAdminInfoAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	@Resource
	private TeamAdminServiceImp teamAdminServiceImp;
	public TeamAdminServiceImp getTeamAdminServiceImp() {
		return teamAdminServiceImp;
	}
	public void setTeamAdminServiceImp(TeamAdminServiceImp teamAdminServiceImp) {
		this.teamAdminServiceImp = teamAdminServiceImp;
	}
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AdminInfoForm adminInfoForm = (AdminInfoForm) form;// TODO Auto-generated method stub
		TeamAdmin ta=teamAdminServiceImp.getTeamAdminByAdname(adminInfoForm.getAdminname());
		if(ta!=null){//说明存在同名的管理员了
			request.setAttribute("res", 0);
		}
		else{
			TeamAdmin t=new TeamAdmin();
			t.setAdemail(adminInfoForm.getAdminemail());
			t.setAdid(adminInfoForm.getAdminid());
			t.setAdname(adminInfoForm.getAdminname());
			teamAdminServiceImp.updateAdminInfo(t);
			request.setAttribute("res", 1);
			TeamAdmin nt=teamAdminServiceImp.getTeamAdminByAdid(adminInfoForm.getAdminid());
			request.getSession().setAttribute("teamadmin",nt);
		}
		return mapping.findForward("ok");
	}
}